### ISSUE TITLE
image_select not working, possibly due to flutter_native_image discontinuation

### ISSUE THREAD

**Issue by Youssf-Mohamed** [thematrixmind/image_selector#1]
I’ve been using the image_select package, and it has stopped working recently. I believe this is because the flutter_native_image package, which is one of its dependencies, has been discontinued.

Could you please look into this issue and consider updating image_select to either replace or remove the flutter_native_image dependency? Any workaround or advice on alternative packages would be appreciated.

#here is the error i get every time i try to build my app

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_native_image:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: G:\shakawa\system\build\flutter_native_image\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 50s
Running Gradle task 'assembleRelease'...                           51.7s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1

**Comment by praveenkumarytc** [comment]
Hi **Youssf-Mohamed**,

Thank you for bringing the issue with the `image_select` package to my attention. I understand that the package has stopped working due to the discontinuation of the `flutter_native_image` dependency, which has led to build errors.

I'm pleased to inform you that I have uploaded a new version, ^0.0.4, of the `image_select` package. This version no longer includes the `flutter_native_image` dependency, addressing the issues you've encountered. 

You can now update to the latest version, and it should work smoothly without the conflicts caused by the deprecated package.

If you have any further questions or need assistance, please feel free to reach out.
